/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiGalleryIndexRouteImport } from './routes/ui-gallery/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UiGalleryViewRouteImport } from './routes/ui-gallery/view'
import { Route as StudySubjectsRouteImport } from './routes/study/subjects'
import { Route as StudyPlannerRouteImport } from './routes/study/planner'
import { Route as StudyNotesRouteImport } from './routes/study/notes'
import { Route as StudyAssignmentsRouteImport } from './routes/study/assignments'
import { Route as SettingsSupportRouteImport } from './routes/settings/support'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsPremiumRouteImport } from './routes/settings/premium'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsFocusRouteImport } from './routes/settings/focus'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiGalleryIndexRoute = UiGalleryIndexRouteImport.update({
  id: '/ui-gallery/',
  path: '/ui-gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiGalleryViewRoute = UiGalleryViewRouteImport.update({
  id: '/ui-gallery/view',
  path: '/ui-gallery/view',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySubjectsRoute = StudySubjectsRouteImport.update({
  id: '/study/subjects',
  path: '/study/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlannerRoute = StudyPlannerRouteImport.update({
  id: '/study/planner',
  path: '/study/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyNotesRoute = StudyNotesRouteImport.update({
  id: '/study/notes',
  path: '/study/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAssignmentsRoute = StudyAssignmentsRouteImport.update({
  id: '/study/assignments',
  path: '/study/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSupportRoute = SettingsSupportRouteImport.update({
  id: '/settings/support',
  path: '/settings/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/settings/storage',
  path: '/settings/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPremiumRoute = SettingsPremiumRouteImport.update({
  id: '/settings/premium',
  path: '/settings/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFocusRoute = SettingsFocusRouteImport.update({
  id: '/settings/focus',
  path: '/settings/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/habits': typeof HabitsRoute
  '/mcp': typeof McpRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/focus': typeof SettingsFocusRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/premium': typeof SettingsPremiumRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/support': typeof SettingsSupportRoute
  '/study/assignments': typeof StudyAssignmentsRoute
  '/study/notes': typeof StudyNotesRoute
  '/study/planner': typeof StudyPlannerRoute
  '/study/subjects': typeof StudySubjectsRoute
  '/ui-gallery/view': typeof UiGalleryViewRoute
  '/settings/': typeof SettingsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/ui-gallery/': typeof UiGalleryIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/habits': typeof HabitsRoute
  '/mcp': typeof McpRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/focus': typeof SettingsFocusRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/premium': typeof SettingsPremiumRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/support': typeof SettingsSupportRoute
  '/study/assignments': typeof StudyAssignmentsRoute
  '/study/notes': typeof StudyNotesRoute
  '/study/planner': typeof StudyPlannerRoute
  '/study/subjects': typeof StudySubjectsRoute
  '/ui-gallery/view': typeof UiGalleryViewRoute
  '/settings': typeof SettingsIndexRoute
  '/study': typeof StudyIndexRoute
  '/ui-gallery': typeof UiGalleryIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/habits': typeof HabitsRoute
  '/mcp': typeof McpRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/focus': typeof SettingsFocusRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/premium': typeof SettingsPremiumRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/support': typeof SettingsSupportRoute
  '/study/assignments': typeof StudyAssignmentsRoute
  '/study/notes': typeof StudyNotesRoute
  '/study/planner': typeof StudyPlannerRoute
  '/study/subjects': typeof StudySubjectsRoute
  '/ui-gallery/view': typeof UiGalleryViewRoute
  '/settings/': typeof SettingsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/ui-gallery/': typeof UiGalleryIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/focus'
    | '/habits'
    | '/mcp'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/focus'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/premium'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/storage'
    | '/settings/support'
    | '/study/assignments'
    | '/study/notes'
    | '/study/planner'
    | '/study/subjects'
    | '/ui-gallery/view'
    | '/settings/'
    | '/study/'
    | '/ui-gallery/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/focus'
    | '/habits'
    | '/mcp'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/focus'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/premium'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/storage'
    | '/settings/support'
    | '/study/assignments'
    | '/study/notes'
    | '/study/planner'
    | '/study/subjects'
    | '/ui-gallery/view'
    | '/settings'
    | '/study'
    | '/ui-gallery'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/focus'
    | '/habits'
    | '/mcp'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/focus'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/premium'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/storage'
    | '/settings/support'
    | '/study/assignments'
    | '/study/notes'
    | '/study/planner'
    | '/study/subjects'
    | '/ui-gallery/view'
    | '/settings/'
    | '/study/'
    | '/ui-gallery/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  FocusRoute: typeof FocusRoute
  HabitsRoute: typeof HabitsRoute
  McpRoute: typeof McpRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsFocusRoute: typeof SettingsFocusRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPremiumRoute: typeof SettingsPremiumRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsSupportRoute: typeof SettingsSupportRoute
  StudyAssignmentsRoute: typeof StudyAssignmentsRoute
  StudyNotesRoute: typeof StudyNotesRoute
  StudyPlannerRoute: typeof StudyPlannerRoute
  StudySubjectsRoute: typeof StudySubjectsRoute
  UiGalleryViewRoute: typeof UiGalleryViewRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  UiGalleryIndexRoute: typeof UiGalleryIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-gallery/': {
      id: '/ui-gallery/'
      path: '/ui-gallery'
      fullPath: '/ui-gallery/'
      preLoaderRoute: typeof UiGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-gallery/view': {
      id: '/ui-gallery/view'
      path: '/ui-gallery/view'
      fullPath: '/ui-gallery/view'
      preLoaderRoute: typeof UiGalleryViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/subjects': {
      id: '/study/subjects'
      path: '/study/subjects'
      fullPath: '/study/subjects'
      preLoaderRoute: typeof StudySubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/planner': {
      id: '/study/planner'
      path: '/study/planner'
      fullPath: '/study/planner'
      preLoaderRoute: typeof StudyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/notes': {
      id: '/study/notes'
      path: '/study/notes'
      fullPath: '/study/notes'
      preLoaderRoute: typeof StudyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/assignments': {
      id: '/study/assignments'
      path: '/study/assignments'
      fullPath: '/study/assignments'
      preLoaderRoute: typeof StudyAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/support': {
      id: '/settings/support'
      path: '/settings/support'
      fullPath: '/settings/support'
      preLoaderRoute: typeof SettingsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/settings/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/premium': {
      id: '/settings/premium'
      path: '/settings/premium'
      fullPath: '/settings/premium'
      preLoaderRoute: typeof SettingsPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/focus': {
      id: '/settings/focus'
      path: '/settings/focus'
      fullPath: '/settings/focus'
      preLoaderRoute: typeof SettingsFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  FocusRoute: FocusRoute,
  HabitsRoute: HabitsRoute,
  McpRoute: McpRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsFocusRoute: SettingsFocusRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPremiumRoute: SettingsPremiumRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsSupportRoute: SettingsSupportRoute,
  StudyAssignmentsRoute: StudyAssignmentsRoute,
  StudyNotesRoute: StudyNotesRoute,
  StudyPlannerRoute: StudyPlannerRoute,
  StudySubjectsRoute: StudySubjectsRoute,
  UiGalleryViewRoute: UiGalleryViewRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  UiGalleryIndexRoute: UiGalleryIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
